export const KNOWN_SKILLS = {
  scrum: { name: "Scrum", kind: "meth", value: 0.9 },
  kanban: { name: "Kanban", kind: "meth", value: 0.8 },
  smart: {
    name: "SMART",
    tooltip: "Specific, Measurable, Achievable, Relevant, Time-bound",
    kind: "meth",
    value: 0.6,
  },
  okr: {
    name: "OKR",
    tooltip: "Objective Key Results",
    kind: "meth",
    value: 1,
  },
  car: {
    name: "CAR",
    tooltip: "Challenge Actions Results",
    kind: "meth",
    value: 1,
  },

  notion: { name: "Notion", kind: "supp", value: 0.9 },
  gSheets: { name: "GSheets", kind: "supp", value: 0.8 },
  jira: { name: "Jira", kind: "supp", value: 0.8 },
  confluence: { name: "Confluence", kind: "supp", value: 0.8 },
  cultureAmp: { name: "CultureAmp", kind: "supp", value: 0.7 },
  looker: { name: "Looker", kind: "supp", value: 0.5 },
  dustAi: { name: "Dust AI", kind: "supp", value: 0.6 },

  aws: { name: "AWS", kind: "prov", value: 0.7 },
  gcp: { name: "GCP", kind: "prov", value: 0.8 },
  heroku: { name: "Heroku", kind: "prov", value: 0.6 },

  ts: { name: "TypeScript", kind: "lang", value: 0.9 },
  js: { name: "JavaScript", kind: "lang", value: 0.8 },
  html: { name: "HTML", kind: "lang", value: 0.9 },
  cpp: { name: "C++", kind: "lang", value: 0.8 },
  cSharp: { name: "C++", kind: "lang", value: 0.7 },
  latex: { name: "Latex", kind: "lang", value: 0.3 },

  node: { name: "Node.js", kind: "fram", value: 0.9 },
  react: { name: "React", kind: "fram", value: 0.9 },
  reactNative: { name: "React Native", kind: "fram", value: 0.3 },
  express: { name: "Express", kind: "fram", value: 0.9 },
  fastify: { name: "Fastify", kind: "fram", value: 0.7 },
  ror: { name: "Ruby on Rails", kind: "fram", value: 0.3 },
  mongoose: { name: "Mongoose", kind: "fram", value: 0.8 },
  bootstrap: { name: "Bootstrap", kind: "fram", value: 0.7 },

  pgsql: { name: "PostgreSQL", kind: "db", value: 0.8 },
  mysql: { name: "MySQL", kind: "db", value: 0.7 },
  redis: { name: "Redis", kind: "db", value: 0.9 },
  mongo: { name: "MongoDB", kind: "db", value: 0.8 },
  bigQuery: { name: "BigQuery", kind: "db", value: 0.5 },
  neo4j: { name: "Neo4J", kind: "db", value: 0.4 },
  couchBase: { name: "CouchBase", kind: "db", value: 0.4 },
  elasticSearch: { name: "ElasticSearch", kind: "db", value: 0.6 },
  aerospike: { name: "Aerospike", kind: "db", value: 0.4 },

  docker: { name: "Docker", kind: "tool", value: 0.8 },
  kube: { name: "Kubernetes", kind: "tool", value: 0.5 },
  terraform: { name: "Terraform", kind: "tool", value: 0.4 },
  kafka: { name: "Kafka", kind: "tool", value: 0.7 },
  pubSub: { name: "Pub/Sub", kind: "tool", value: 0.7 },
  travis: { name: "Travis", kind: "tool", value: 0.8 },
} as const;
